image: donaldm314/ubuntu-bats:101
options:
    max-time: 1
pipelines:
    default:
        - step:
            name: "Test"
            script:
                - wget https://github.com/go-task/task/releases/download/v3.38.0/task_linux_amd64.deb
                - dpkg -i task_linux_amd64.deb
                - task

