# https://taskfile.dev

version: '3.38'

interval: '100ms'

vars:

tasks:
  default:
    deps: [check, test]

  check:
    watch: true
    sources:
      - '**/*.sh'
      - '**/*.bats'
    cmds:
      - shellcheck *.sh

  test:
    watch: true
    sources:
      - '**/*.sh'
      - '**/*.bats'
    cmds:
      - bats **/*.bats

  clean:
    cmds:
     - rm -f *.log *~