name: CI
on:
  push:
    branches: [main]

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    container:
      image: donaldm314/ubuntu-bats:102
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: "Test"
        run: |
          task
          ls -lart
          id
